# This is meant for local development only. Do not use this in production.
name: cap-so-dev

services:
  postgres:
    container_name: postgres-primary-db
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: capso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Using Supabase Storage for file storage
volumes:
  postgres_data:
